export const FORMATS={vertical:{w:1080,h:1920,label:'9:16'},square:{w:1080,h:1080,label:'1:1'},landscape:{w:1920,h:1080,label:'16:9'}};
function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function wrapRtl(ctx,text,maxWidth){const words=text.trim().split(/\s+/);const lines=[];let cur='';for(const word of words){const next=cur?`${word} ${cur}`:word; if(ctx.measureText(next).width<=maxWidth)cur=next;else{if(cur)lines.push(cur);cur=word}}if(cur)lines.push(cur);return lines}
export function drawFrame(ctx,canvas,image,state,ayah,translation,opts={}){
  const {w,h}=canvas;ctx.clearRect(0,0,w,h);
  if(image){const iw=image.naturalWidth||image.width,ih=image.naturalHeight||image.height;const scale=state.fit==='contain'?Math.min(w/iw,h/ih):Math.max(w/iw,h/ih);const dw=iw*scale,dh=ih*scale;ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.drawImage(image,(w-dw)/2,(h-dh)/2,dw,dh)}else{const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#15191e');g.addColorStop(1,'#080a0d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
  if(opts.overlay>0){ctx.fillStyle=`rgba(0,0,0,${opts.overlay})`;ctx.fillRect(0,0,w,h)}
  if(!ayah)return;
  const scale=Math.min(w/1080,h/1920);const family=state.font;const arabicSize=state.arabicSize*scale;const transSize=state.translationSize*scale;const maxWidth=w*0.86;
  ctx.textAlign='center';ctx.direction='rtl';ctx.textBaseline='middle';ctx.fillStyle=state.color;ctx.font=`700 ${arabicSize}px "${family}", serif`;
  const arabicLines=wrapRtl(ctx,ayah.text,maxWidth);const lineH=arabicSize*1.35;const aX=state.positions.arabic.x*w,aY=state.positions.arabic.y*h;const aBoxH=arabicLines.length*lineH;
  ctx.shadowColor='rgba(0,0,0,.72)';ctx.shadowBlur=Math.max(4,9*scale);ctx.shadowOffsetY=2*scale;arabicLines.forEach((line,i)=>ctx.fillText(line,aX,aY+(i-(arabicLines.length-1)/2)*lineH));
  ctx.shadowBlur=0;ctx.shadowOffsetY=0;
  if(opts.showTranslation&&translation){ctx.font=`500 ${transSize}px Inter, sans-serif`;ctx.fillStyle='#f3efe6';const tLines=wrapRtl(ctx,translation,maxWidth*0.88);const tH=transSize*1.35;const tX=state.positions.translation.x*w;const tY=state.positions.translation.y*h;ctx.direction='ltr';tLines.forEach((line,i)=>ctx.fillText(line,tX,tY+(i-(tLines.length-1)/2)*tH))}
  ctx.font=`500 ${Math.max(20,22*scale)}px Inter, sans-serif`;ctx.fillStyle='rgba(255,248,231,.9)';ctx.direction='ltr';ctx.fillText(`${ayah.surah.number}:${ayah.numberInSurah}`,w/2,h*0.93);
}
export function getTextBoxes(canvas,ayah,translation,state,showTranslation){const {w,h}=canvas;const scale=Math.min(w/1080,h/1920);const ctx=canvas.getContext('2d');ctx.font=`700 ${state.arabicSize*scale}px "${state.font}", serif`;const lines=wrapRtl(ctx,ayah?.text||'',w*.86);const lh=state.arabicSize*scale*1.35;const arabicW=Math.min(w*.86,Math.max(...lines.map(x=>ctx.measureText(x).width),0)+20);const arabicH=Math.max(lh,lines.length*lh);const a={x:state.positions.arabic.x*w,y:state.positions.arabic.y*h,w:arabicW,h:arabicH};let t=null;if(showTranslation&&translation){ctx.font=`500 ${state.translationSize*scale}px Inter, sans-serif`;const tl=wrapRtl(ctx,translation,w*.76);const th=state.translationSize*scale*1.35;t={x:state.positions.translation.x*w,y:state.positions.translation.y*h,w:Math.min(w*.76,Math.max(...tl.map(x=>ctx.measureText(x).width),0)+20),h:Math.max(th,tl.length*th)}}return {arabic:a,translation:t}}
