import {getSurahs,getSurahText,getSurahTranslation,getTranslations,getReciters} from './api.js';
import {FORMATS,drawFrame,getTextBoxes} from './canvasRenderer.js';
import {renderVideo} from './export.js';

const $=s=>document.querySelector(s);const canvas=$('#previewCanvas');const ctx=canvas.getContext('2d');
const els={bg:$('#backgroundInput'),fit:$('#fitMode'),overlay:$('#overlayRange'),surah:$('#surahSelect'),from:$('#fromVerse'),to:$('#toVerse'),font:$('#fontSelect'),arabicSize:$('#arabicSize'),translationSize:$('#translationSize'),arabicSizeOut:$('#arabicSizeOut'),translationSizeOut:$('#translationSizeOut'),color:$('#textColor'),translationToggle:$('#translationToggle'),translation:$('#translationSelect'),reciter:$('#reciterSelect'),status:$('#status'),download:$('#downloadBtn'),progressWrap:$('#progressWrap'),progressBar:$('#progressBar'),ayahIndicator:$('#ayahIndicator'),formatMeta:$('#previewMeta'),canvasWrap:$('#canvasWrap')};
const state={format:'vertical',fit:'cover',overlay:.2,font:'Amiri',arabicSize:58,translationSize:26,color:'#FFF8E7',showTranslation:false,translationEdition:'en.sahih',reciter:'ar.alafasy',positions:{arabic:{x:.5,y:.58},translation:{x:.5,y:.77}},surahs:[],verses:[],translations:[],audioEdition:'ar.alafasy',current:0,image:null};
let drag=null,previewTimer=null;
function setStatus(msg,kind=''){els.status.textContent=msg;els.status.className=`status ${kind}`}
function syncCanvas(){const f=FORMATS[state.format];canvas.width=f.w;canvas.height=f.h;els.canvasWrap.className=`canvas-wrap ${state.format}`;els.formatMeta.textContent=`${f.label} • ${f.w}×${f.h}`;drawCurrent()}
function drawCurrent(){const v=state.verses[state.current];const tr=state.translations[state.current]?.text||'';drawFrame(ctx,canvas,state.image,state,v,state.showTranslation?tr:'',{overlay:state.overlay,showTranslation:state.showTranslation});els.ayahIndicator.textContent=v?`${v.numberInSurah} / ${state.verses.length}`:'—';const dl=$('#dragLabel');dl.style.opacity=v?'0':'0.9'}
function populateVerses(){const s=state.surahs.find(x=>x.number===Number(els.surah.value));if(!s)return;els.from.innerHTML='';els.to.innerHTML='';for(let i=1;i<=s.numberOfAyahs;i++){els.from.add(new Option(i,i));els.to.add(new Option(i,i))}els.from.value='1';els.to.value=String(s.numberOfAyahs);loadContent()}
async function loadContent(){const sn=Number(els.surah.value);if(!sn)return;els.download.disabled=true;setStatus('Loading Quran text and selected translation…');try{const [arabic,trans]=await Promise.all([getSurahText(sn),getSurahTranslation(sn,state.translationEdition)]);const from=Number(els.from.value||1),to=Number(els.to.value||arabic.ayahs.length);state.verses=arabic.ayahs.filter(a=>a.numberInSurah>=from&&a.numberInSurah<=to).map(a=>({...a,globalNumber:a.number}));state.translations=trans.ayahs.filter(a=>a.numberInSurah>=from&&a.numberInSurah<=to);state.current=0;els.download.disabled=!(state.image&&state.verses.length);setStatus('Ready. Drag the Quran text on the preview.','ok');drawCurrent()}catch(e){console.error(e);setStatus('Could not load Quran data. Check your connection.','error')}}
async function init(){try{state.surahs=await getSurahs();els.surah.innerHTML=state.surahs.map(s=>`<option value="${s.number}">${s.number}. ${s.name.replace(/[ٱٰ]/g,'').trim()} — ${s.englishName}</option>`).join('');els.surah.disabled=false;els.surah.value='36';populateVerses()}catch(e){setStatus('Could not connect to the Quran API.','error')}
try{const ts=await getTranslations();const preferred=['en.sahih','en.clearquran','en.yusufali'];const sorted=[...ts.filter(x=>preferred.includes(x.identifier)),...ts.filter(x=>!preferred.includes(x.identifier))];els.translation.innerHTML=sorted.map(x=>`<option value="${x.identifier}">${x.languageName||x.language} — ${x.englishName}</option>`).join('');els.translation.value='en.sahih'}catch(e){els.translation.innerHTML='<option value="en.sahih">English — Saheeh International</option>'}
try{const rs=await getReciters();const preferred=rs.find(x=>x.identifier==='ar.alafasy');const rest=rs.filter(x=>x.identifier!=='ar.alafasy');els.reciter.innerHTML=(preferred?[preferred]:[]).concat(rest).map(x=>`<option value="${x.identifier}">${x.englishName||x.name}</option>`).join('');if(preferred)els.reciter.value='ar.alafasy';els.reciter.disabled=false}catch(e){setStatus('Could not load reciters.','error')}syncCanvas()}
els.bg.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const img=new Image();img.onload=()=>{state.image=img;els.download.disabled=!state.verses.length;setStatus('Background loaded. Drag the text to position it.','ok');drawCurrent()};img.src=URL.createObjectURL(file)});
els.fit.addEventListener('change',e=>{state.fit=e.target.value;drawCurrent()});els.overlay.addEventListener('input',e=>{state.overlay=Number(e.target.value);drawCurrent()});
$('#formatGroup').addEventListener('click',e=>{const b=e.target.closest('button[data-format]');if(!b)return;document.querySelectorAll('#formatGroup button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.format=b.dataset.format;syncCanvas()});
els.surah.addEventListener('change',populateVerses);els.from.addEventListener('change',loadContent);els.to.addEventListener('change',loadContent);els.font.addEventListener('change',e=>{state.font=e.target.value;drawCurrent()});els.arabicSize.addEventListener('input',e=>{state.arabicSize=Number(e.target.value);els.arabicSizeOut.value=state.arabicSize;drawCurrent()});els.translationSize.addEventListener('input',e=>{state.translationSize=Number(e.target.value);els.translationSizeOut.value=state.translationSize;drawCurrent()});els.color.addEventListener('input',e=>{state.color=e.target.value;document.querySelectorAll('.swatch').forEach(s=>s.classList.remove('active'));drawCurrent()});document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{state.color=b.dataset.color;els.color.value=b.dataset.color;document.querySelectorAll('.swatch').forEach(s=>s.classList.remove('active'));b.classList.add('active');drawCurrent()}));
els.translationToggle.addEventListener('change',e=>{state.showTranslation=e.target.checked;els.translation.disabled=!state.showTranslation;drawCurrent()});els.translation.addEventListener('change',e=>{state.translationEdition=e.target.value;loadContent()});els.reciter.addEventListener('change',e=>state.audioEdition=e.target.value);
$('#resetPositions').addEventListener('click',()=>{state.positions={arabic:{x:.5,y:.58},translation:{x:.5,y:.77}};drawCurrent()});$('#prevAyah').addEventListener('click',()=>{if(!state.verses.length)return;state.current=Math.max(0,state.current-1);drawCurrent()});$('#nextAyah').addEventListener('click',()=>{if(!state.verses.length)return;state.current=Math.min(state.verses.length-1,state.current+1);drawCurrent()});
canvas.addEventListener('pointerdown',e=>{const v=state.verses[state.current];if(!v)return;const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;const tr=state.showTranslation?state.translations[state.current]?.text:'';const boxes=getTextBoxes(canvas,v,tr,state,state.showTranslation);for(const [type,b] of Object.entries(boxes)){if(!b)continue;if(x>=b.x-b.w/2&&x<=b.x+b.w/2&&y>=b.y-b.h/2&&y<=b.y+b.h/2){drag={type,dx:x-b.x,dy:y-b.y};canvas.setPointerCapture(e.pointerId);break}}});canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*canvas.width-drag.dx,y=(e.clientY-r.top)/r.height*canvas.height-drag.dy;state.positions[drag.type].x=Math.max(.08,Math.min(.92,x/canvas.width));state.positions[drag.type].y=Math.max(.1,Math.min(.9,y/canvas.height));drawCurrent()});['pointerup','pointercancel','pointerleave'].forEach(ev=>canvas.addEventListener(ev,()=>drag=null));
function stopPreview(){if(previewTimer){clearInterval(previewTimer);previewTimer=null}}
$('#playPreview').addEventListener('click',()=>{if(!state.verses.length)return;stopPreview();state.current=0;drawCurrent();let start=Date.now();previewTimer=setInterval(()=>{const elapsed=(Date.now()-start)/1000;const idx=Math.min(state.verses.length-1,Math.floor(elapsed/3));if(idx!==state.current){state.current=idx;drawCurrent()}if(idx>=state.verses.length-1){stopPreview()}},100)});$('#stopPreview').addEventListener('click',stopPreview);
els.download.addEventListener('click',async()=>{if(!state.image||!state.verses.length)return;stopPreview();els.download.disabled=true;els.progressWrap.classList.remove('hidden');els.progressBar.style.width='0%';try{const blob=await renderVideo({canvas,image:state.image,state,verses:state.verses,translations:state.translations,audioEdition:state.audioEdition,onProgress:(p,m)=>{els.progressBar.style.width=`${p}%`;setStatus(`${m} ${p}%`);},draw:i=>{state.current=i;drawCurrent()}});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`quran-${state.verses[0].surah.number}-${state.verses.at(-1).numberInSurah}-${FORMATS[state.format].label.replace(':','x')}.webm`;a.click();URL.revokeObjectURL(a.href);setStatus('Video ready and downloaded.','ok')}catch(e){console.error(e);setStatus(e.message||'Export failed.','error')}finally{els.download.disabled=false}});
init();
